### ISSUE TITLE
Increasing Memory Size Problem

### ISSUE THREAD

**Issue by dmadhitama** [JusperLee/Dual-Path-RNN-Pytorch#20]
Hello there,

I was using this repo, trying to resume training your pretrained model using my own dataset. I already prepared the dataset as the readme tutorial guided. The problem now is; I ran the `train_rnn.py` script. Yes, I successfully run and freeze at:

```
20-09-29 15:51:21 [train_rnn.py:66 - INFO ] Building the model of Dual-Path-RNN
20-09-29 15:51:21 [train_rnn.py:69 - INFO ] Building the optimizer of Dual-Path-RNN
20-09-29 15:51:21 [train_rnn.py:72 - INFO ] Building the dataloader of Dual-Path-RNN
```

It's been an hour and I saw the htop my RAM increasing above 211G. Is this normal or the script is running the dataset on the fly?

**Comment by JusperLee** [comment]
If it is a large data set, I recommend you to use this script's Dataset. Because my script will read data into memory, which is not friendly for large data sets.
https://github.com/JusperLee/Conv-TasNet/blob/master/Conv-TasNet_lightning/Datasets.py

**Comment by dmadhitama** [comment]
Hey @JusperLee thank you for the reply!

I've managed to replace the Dataset script using the script you provided. However, this error occurred:
```
20-10-05 19:01:01 [train_rnn.py:67 - INFO ] Building the model of Dual-Path-RNN
20-10-05 19:01:01 [train_rnn.py:70 - INFO ] Building the optimizer of Dual-Path-RNN
20-10-05 19:01:01 [train_rnn.py:73 - INFO ] Building the dataloader of Dual-Path-RNN
20-10-05 19:40:26 [train_rnn.py:77 - INFO ] Train Datasets Length: 138766, Val Datasets Length: 34980
20-10-05 19:40:26 [train_rnn.py:86 - INFO ] Building the Trainer of Dual-Path-RNN
20-10-05 19:40:26 [/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py:35 - INFO ] Load Nvida GPU .....
20-10-05 19:40:35 [/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py:41 - INFO ] Loading Dual-Path-RNN parameters: 2.634 Mb
20-10-05 19:40:36 [/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py:54 - INFO ] Resume from checkpoint /home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/exp1/checkpoint/Dual_Path_RNN: epoch 46.000
20-10-05 19:40:37 [/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py:69 - INFO ] Gradient clipping by 5, default L2
20-10-05 19:40:37 [/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py:116 - INFO ] Start Validation from epoch: 46, iter: 0
Traceback (most recent call last):
  File "train_rnn.py", line 92, in <module>
    train()
  File "train_rnn.py", line 88, in train
    trainer.run()
  File "/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py", line 158, in run
    best_loss = v_loss
  File "/home/donny.adhitama/dom_tools/Dual-Path-RNN-Pytorch/trainer/trainer_Dual_RNN.py", line 127, in validation
    ref = [ref[i].to(self.device) for i in range(self.num_spks)]
AttributeError: 'str' object has no attribute 'to'
```

The `mix` and `ref` variable is yielding string values. Why this is happen?
