### ISSUE TITLE
关于运行train_rnn.py的问题

### ISSUE THREAD

**Issue by kikibros** [JusperLee/Dual-Path-RNN-Pytorch#48]
C:\Users\yhq\.conda\envs\pytorch\python.exe D:/Dual-Path-RNN-Pytorch-master/Dual-Path-RNN-Pytorch-master/train_rnn.py
C:\Users\yhq\.conda\envs\pytorch\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
Traceback (most recent call last):
  File "D:/Dual-Path-RNN-Pytorch-master/Dual-Path-RNN-Pytorch-master/train_rnn.py", line 91, in <module>
    train()
  File "D:/Dual-Path-RNN-Pytorch-master/Dual-Path-RNN-Pytorch-master/train_rnn.py", line 61, in train
    opt = option.parse(args.opt)
  File "D:\Dual-Path-RNN-Pytorch-master\Dual-Path-RNN-Pytorch-master\config\option.py", line 4, in parse
    with open(opt_path, mode='r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Process finished with exit code 1
请问一下出现这个错误怎么解决，或者说是哪方面出现了问题，求答复，感谢！

**Comment by JusperLee** [comment]
应该是未检测到opt_path的输入文件路径
