### ISSUE TITLE
关于音频读入的问题

### ISSUE THREAD

**Issue by FBSalol** [JusperLee/Dual-Path-RNN-Pytorch#60]
作者你好，我在加载音频时，读入的src参数维数不是二维，此问题在加载不同音频时时有时无，请问作者遇到过类似的问题吗，是如何解决的呢？谢谢
![280b90e5d4ef5ff095301789b3889bb](https://github.com/JusperLee/Dual-Path-RNN-Pytorch/assets/139541059/d6ff5d56-7e73-42f2-948c-810dc846cc4c)
Traceback (most recent call last):
  File "D:\model\Dual-Path-RNN-Pytorch-master\Dual-Path-RNN-Pytorch-master\dualrnn_test_wav.py", line 73, in <module>
    main()
  File "D:\model\Dual-Path-RNN-Pytorch-master\Dual-Path-RNN-Pytorch-master\dualrnn_test_wav.py", line 69, in main
    separation.inference(args.save_path)
  File "D:\model\Dual-Path-RNN-Pytorch-master\Dual-Path-RNN-Pytorch-master\dualrnn_test_wav.py", line 50, in inference
    write_wav(filename, s, 16000)
  File "D:\model\Dual-Path-RNN-Pytorch-master\Dual-Path-RNN-Pytorch-master\data_loader\AudioReader.py", line 37, in write_wav
    torchaudio.save(fname, src, sample_rate)
  File "C:\Users\dell\AppData\Local\conda\conda\envs\d2l\lib\site-packages\torchaudio\_backend\utils.py", line 288, in save
    return backend.save(uri, src, sample_rate, channels_first, format, encoding, bits_per_sample, buffer_size)
  File "C:\Users\dell\AppData\Local\conda\conda\envs\d2l\lib\site-packages\torchaudio\_backend\soundfile.py", line 39, in save
    soundfile_backend.save(
  File "C:\Users\dell\AppData\Local\conda\conda\envs\d2l\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 427, in save
    raise ValueError(f"Expected 2D Tensor, got {src.ndim}D.")
ValueError: Expected 2D Tensor, got 1D.

**Comment by JusperLee** [comment]
你可以用view(B, 2, T)

**Comment by heyun913** [comment]
hello ，解决了么，遇到了同样的问题

**Comment by FBSalol** [comment]
> hello ，解决了么，遇到了同样的问题

没有，估计大概率是音频的原因，我使用自己录制的音频就不会出现此问题，你可以看看作者提供的混合音频的代码
