### ISSUE TITLE
修改音源数量后进行训练

### ISSUE THREAD

**Issue by 17866526430** [JusperLee/Dual-Path-RNN-Pytorch#66]
您好，我将音源数量修改为了8个，遇到了这样的问题，但是在运行option.py文件时也没有报错，请问您知道是为什么吗？
![Uploading 微信图片_20241123214033.png…]()

**Comment by 17866526430** [comment]
(myenv) (base) root@lr0114:/home/Dual-Path-RNN-Pytorch-master# /root/anaconda3/envs/myenv/bin/python /home/Dual-Path-RNN-Pytorch-master/train_rnn.py
Traceback (most recent call last):
  File "/home/Dual-Path-RNN-Pytorch-master/train_rnn.py", line 103, in <module>
    train()
  File "/home/Dual-Path-RNN-Pytorch-master/train_rnn.py", line 73, in train
    opt = option.parse(args.opt)
  File "/home/Dual-Path-RNN-Pytorch-master/config/option.py", line 4, in parse
    with open(opt_path, mode='r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by JusperLee** [comment]
已经邮件回复了

祝好
